# Generated by Django 2.0.5 on 2018-05-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(max_length=30)),
                ('post_title', models.CharField(max_length=30)),
                ('post_html_text', models.CharField(max_length=5000)),
                ('post_description', models.CharField(max_length=30)),
                ('post_date', models.DateTimeField()),
            ],
        ),
    ]
